[package]
name = "device-code"
version = "0.1.0"
authors = ["sagonzal"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
msal = { path = "../../"}